sets = {
    "Return to Ravnica": "rtr",
    "Avacyn Restored": "avr",
    "Dark Ascension": "dka",
    "Innistrad": "isd",
    "New Phyrexia": "nph",
    "Mirrodin Besieged": "mbs",
    "Scars of Mirrodin": "som",
    "Rise of the Eldrazi": "roe",
    "Worldwake": "wwk",
    "Zendikar": "zen",
    "Alara Reborn": "arb",
    "Conflux": "cfx",
    "Shards of Alara": "ala",
    "Eventide": "eve",
    "Shadowmoor": "shm",
    "Morningtide": "mt",
    "Lorwyn": "lw",
    "Future Sight": "fut",
    "Planar Chaos": "pc",
    "Time Spiral": "ts",
    "Time Spiral \"Timeshifted\"": "tsts",
    "Coldsnap": "cs",
    "Alliances": "ai",
    "Ice Age": "ia",
    "Dissension": "di",
    "Guildpact": "gp",
    "Ravnica: City of Guilds": "rav",
    "Saviors of Kamigawa": "sok",
    "Betrayers of Kamigawa": "bok",
    "Champions of Kamigawa": "chk",
    "Fifth Dawn": "5dn",
    "Darksteel": "ds",
    "Mirrodin": "mi",
    "Scourge": "sc",
    "Legions": "le",
    "Onslaught": "on",
    "Judgment": "ju",
    "Torment": "tr",
    "Odyssey": "od",
    "Apocalypse": "ap",
    "Planeshift": "ps",
    "Invasion": "in",
    "Prophecy": "pr",
    "Nemesis": "ne",
    "Mercadian Masques": "mm",
    "Urza's Destiny": "ud",
    "Urza's Legacy": "ul",
    "Urza's Saga": "us",
    "Exodus": "ex",
    "Stronghold": "sh",
    "Tempest": "tp",
    "Weatherlight": "wl",
    "Visions": "vi",
    "Mirage": "mr",
    "Homelands": "hl",
    "Fallen Empires": "fe",
    "The Dark": "dk",
    "Legends": "lg",
    "Antiquities": "aq",
    "Arabian Nights": "an",
    "Magic 2013": "m13",
    "Magic 2012": "m12",
    "Magic 2011": "m11",
    "Magic 2010": "m10",
    "Tenth Edition": "10e",
    "Ninth Edition": "9e",
    "Eighth Edition": "8e",
    "Seventh Edition": "7e",
    "Classic Sixth Edition": "6e",
    "Fifth Edition": "5e",
    "Fourth Edition": "4e",
    "Revised Edition": "rv",
    "Unlimited Edition": "un",
    "Limited Edition Beta": "be",
    "Limited Edition Alpha": "al",
    "Unhinged": "uh",
    "Unglued": "ug",
    "Starter 2000": "st2k",
    "Starter 1999": "st",
    "Portal Three Kingdoms": "p3k",
    "Portal Second Age": "po2",
    "Portal": "po",
    "From the Vault: Realms": "v12",
    "From the Vault: Legends": "fvl",
    "From the Vault: Relics": "fvr",
    "From the Vault: Exiled": "fve",
    "From the Vault: Dragons": "fvd",
    "Duel Decks: Izzet vs. Golgari": "ddj",
    "Duel Decks: Venser vs. Koth": "ddi",
    "Duel Decks: Ajani vs. Nicol Bolas": "ddh",
    "Duel Decks: Knights vs. Dragons": "ddg",
    "Duel Decks: Elspeth vs. Tezzeret": "ddf",
    "Duel Decks: Phyrexia vs. The Coalition": "pvc",
    "Duel Decks: Garruk vs. Liliana": "gvl",
    "Duel Decks: Divine vs. Demonic": "dvd",
    "Duel Decks: Jace vs. Chandra": "jvc",
    "Duel Decks: Elves vs. Goblins": "evg",
    "Ninth Edition Box Set": "9eb",
    "Eighth Edition Box Set": "8eb",
    "Deckmasters": "dm",
    "Beatdown Box Set": "bd",
    "Battle Royale Box Set": "br",
    "Anthologies": "at",
    "Multiverse Gift Box Cards": "mgbc",
    "Premium Deck Series: Graveborn": "pd3",
    "Premium Deck Series: Fire and Lightning": "pd2",
    "Premium Deck Series: Slivers": "pds",
    "Duels of the Planeswalkers": "dpa",
    "Chronicles": "ch",
    "Planechase 2012 Edition": "pc2",
    "Commander": "cmd",
    "Archenemy": "arc",
    "Planechase": "pch",
    "Coldsnap Theme Decks": "cstd",
}