sets = {
    u"Born of the Gods": u"bgn",
    u"Theros": u"ths",
    u"Dragon's Maze": u"dgm",
    u"Gatecrash": u"gtc",
    u"Return to Ravnica": u"rtr",
    u"Avacyn Restored": u"avr",
    u"Dark Ascension": u"dka",
    u"Innistrad": u"isd",
    u"New Phyrexia": u"nph",
    u"Mirrodin Besieged": u"mbs",
    u"Scars of Mirrodin": u"som",
    u"Rise of the Eldrazi": u"roe",
    u"Worldwake": u"wwk",
    u"Zendikar": u"zen",
    u"Alara Reborn": u"arb",
    u"Conflux": u"cfx",
    u"Shards of Alara": u"ala",
    u"Eventide": u"eve",
    u"Shadowmoor": u"shm",
    u"Morningtide": u"mt",
    u"Lorwyn": u"lw",
    u"Future Sight": u"fut",
    u"Planar Chaos": u"pc",
    u"Time Spiral": u"ts",
    u"Time Spiral \"Timeshifted\"": u"tsts",
    u"Coldsnap": u"cs",
    u"Alliances": u"ai",
    u"Ice Age": u"ia",
    u"Dissension": u"di",
    u"Guildpact": u"gp",
    u"Ravnica: City of Guilds": u"rav",
    u"Saviors of Kamigawa": u"sok",
    u"Betrayers of Kamigawa": u"bok",
    u"Champions of Kamigawa": u"chk",
    u"Fifth Dawn": u"5dn",
    u"Darksteel": u"ds",
    u"Mirrodin": u"mi",
    u"Scourge": u"sc",
    u"Legions": u"le",
    u"Onslaught": u"on",
    u"Judgment": u"ju",
    u"Torment": u"tr",
    u"Odyssey": u"od",
    u"Apocalypse": u"ap",
    u"Planeshift": u"ps",
    u"Invasion": u"in",
    u"Prophecy": u"pr",
    u"Nemesis": u"ne",
    u"Mercadian Masques": u"mm",
    u"Urza's Destiny": u"ud",
    u"Urza's Legacy": u"ul",
    u"Urza's Saga": u"us",
    u"Exodus": u"ex",
    u"Stronghold": u"sh",
    u"Tempest": u"tp",
    u"Weatherlight": u"wl",
    u"Visions": u"vi",
    u"Mirage": u"mr",
    u"Homelands": u"hl",
    u"Fallen Empires": u"fe",
    u"The Dark": u"dk",
    u"Legends": u"lg",
    u"Antiquities": u"aq",
    u"Arabian Nights": u"an",
    u"Magic 2013": u"m13",
    u"Magic 2012": u"m12",
    u"Magic 2011": u"m11",
    u"Magic 2010": u"m10",
    u"Tenth Edition": u"10e",
    u"Ninth Edition": u"9e",
    u"Eighth Edition": u"8e",
    u"Seventh Edition": u"7e",
    u"Classic Sixth Edition": u"6e",
    u"Fifth Edition": u"5e",
    u"Fourth Edition": u"4e",
    u"Revised Edition": u"rv",
    u"Unlimited Edition": u"un",
    u"Limited Edition Beta": u"be",
    u"Limited Edition Alpha": u"al",
    u"Unhinged": u"uh",
    u"Unglued": u"ug",
    u"Starter 2000": u"st2k",
    u"Starter 1999": u"st",
    u"Portal Three Kingdoms": u"p3k",
    u"Portal Second Age": u"po2",
    u"Portal": u"po",
    u"From the Vault: Realms": u"v12",
    u"From the Vault: Legends": u"fvl",
    u"From the Vault: Relics": u"fvr",
    u"From the Vault: Exiled": u"fve",
    u"From the Vault: Dragons": u"fvd",
    u"Duel Decks: Izzet vs. Golgari": u"ddj",
    u"Duel Decks: Venser vs. Koth": u"ddi",
    u"Duel Decks: Ajani vs. Nicol Bolas": u"ddh",
    u"Duel Decks: Knights vs. Dragons": u"ddg",
    u"Duel Decks: Elspeth vs. Tezzeret": u"ddf",
    u"Duel Decks: Phyrexia vs. the Coalition": u"pvc",
    u"Duel Decks: Garruk vs. Liliana": u"gvl",
    u"Duel Decks: Divine vs. Demonic": u"dvd",
    u"Duel Decks: Jace vs. Chandra": u"jvc",
    u"Duel Decks: Elves vs. Goblins": u"evg",
    u"Ninth Edition Box Set": u"9eb",
    u"Eighth Edition Box Set": u"8eb",
    u"Deckmasters": u"dm",
    u"Beatdown Box Set": u"bd",
    u"Battle Royale Box Set": u"br",
    u"Anthologies": u"at",
    u"Multiverse Gift Box Cards": u"mgbc",
    u"Premium Deck Series: Graveborn": u"pd3",
    u"Premium Deck Series: Fire and Lightning": u"pd2",
    u"Premium Deck Series: Slivers": u"pds",
    u"Duels of the Planeswalkers": u"dpa",
    u"Chronicles": u"ch",
    u"Planechase 2012 Edition": u"pc2",
    u"Magic: The Gathering-Commander": u"cmd",
    u"Archenemy": u"arc",
    u"Planechase": u"pch",
    u"Coldsnap Theme Decks": u"cstd",
}
